# Site
# repository: 
# favicon: 

# Personal info
name: Jorge Gabriel Siqueira
title: Software Developer Engineer
# email: 
# phone: 
# cv   : 
# website: 

# Social links
github_username:  jgsiqueira
linkedin_username: jgabrielsiqueira
# youtube_username: channel/UCSuGoO_f1gyI9bniHuZlNpA/videos
# facebook_username: 
# instagram_username: 
# twitter_username:
# dribbble_username: 
# flickr_username: 
# xing_username: 
# pinterest_username: 
# googleplus_username: 

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Passionated by technology and programming.

  Main skills:
    - Programming (Java, C, Python)
    - Distributed Systems
    - Growth Hacking
    - A/B Testing
    - Currently studying a lot about `Machine Learning`

# Projects Section
projects_title: Awards

# Experience Section
experience_title: Experience

# Education Section
education_title: Education

# More Section
more_title: A Little More About Me
more_content: |
  Apart from technology and programming, I love playing with my dogs!

  For sports, I am currently in love with Brazilian Jiu-Jitsu (BJJ).

  As a hobby, I am spending a lot of time studyng about photography and video making.

# Footer
footer_show_references: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jemoji

exclude : [
  "makefile",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
